### ISSUE TITLE
ImportError: cannot import name 'kmer_count' from 'src.tools' (unknown location)

### ISSUE THREAD

**Issue by XiaomengWang0413** [WeiliWw/VirHostMatcher-Net#26]
Hello, I have run the line of code of dependency condition, but the following error still appears. May I ask what is the problem?
Traceback (most recent call last):
  File "VirHostMatcher-Net.py", line 54, in <module>
    from predictor import HostPredictor     
  File "/home/xiaomeng/biosoft/VirHostMatcher-Net/predictor.py", line 4, in <module>
    import src.s2star
  File "/home/xiaomeng/biosoft/VirHostMatcher-Net/src/s2star.py", line 9, in <module>
    from .tools import kmer_count
ImportError: cannot import name 'kmer_count' from 'src.tools' (unknown location)

**Comment by WoCer2019** [comment]
The same error!

**Comment by miczuppi** [comment]
Same here, did you manage to sort this out?

**Comment by miczuppi** [comment]
A coworker helped me sort this out. The installation code for the src/ folder provided is
`CC=g++ python setup.py install --install-platlib=./src/` which apparently is a typo. 
Running `CC=g++` and `python setup.py install --install-platlib=./src/` separately solves this issue. 
Hope this was helpful

**Comment by XiaominWang12** [comment]
How did you download the database?
